### ISSUE TITLE
Unable to import in Swift project

### ISSUE THREAD

**Issue by dkharrat** [melke/LogglyLogger-CocoaLumberjack#16]
I'm using CocoaPod to import LogglyLogger-CocoaLumberjack in a Swift project, but I wasn't able to get the project to compile. When adding this file to my project's Bridging-Header file:

```objc
#import <LogglyLogger_CocoaLumberjack/LogglyLogger.h>
```

I get the following error when building:

```
LogglyLogger_CocoaLumberjack.framework/Headers/LogglyLogger.h:7:9: error: 'DDAbstractDatabaseLogger.h' file not found
#import "DDAbstractDatabaseLogger.h"
```

I was able to make it work by changing the include line in LogglyLogger.h as follows:

```diff
- #import "DDAbstractDatabaseLogger.h"
+ #import <CocoaLumberjack/DDAbstractDatabaseLogger.h>
```

Is there a reason why the current include format is used? Can it be changed to the full path as I did above?

**Comment by melke** [comment]
Thanks! It's definitely a bug. I will use your bugfix and release a new version. Thanks for reporting!

**Comment by dkharrat** [comment]
Awesome, thanks!

**Comment by qadirsuh** [comment]
@melke can you please share the swift code you have implemented in your project. thank you
