### ISSUE TITLE
Crash in iOS app when CFBundleDisplayName is not defined in Info.plist

### ISSUE THREAD

**Issue by dkharrat** [melke/LogglyLogger-CocoaLumberjack#17]
As I was trying to integrate LogglyLogger-CocoaLumberjack into my project, I got a crash in the following line in LogglyFields.m:

```objc
[dict setObject:[[[NSBundle mainBundle] infoDictionary] objectForKey:@"CFBundleDisplayName"] forKey:@"appname"];
```

The reason is `CFBundleDisplayName` is not defined in the bundle:

```
2015-04-09 01:47:55.802 App[13287:2095219] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** setObjectForKey: object cannot be nil (key: appname)'
```

Based on [Apple's documentation](https://developer.apple.com/library/ios/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/plist/info/CFBundleDisplayName), `CFBundleDisplayName` is optional, so it's not safe for one to assume it's defined. A better and reliable key to use is `CFBundleName`, which is guaranteed to be defined. This fixes the crash for me.

```diff
- [dict setObject:[[[NSBundle mainBundle] infoDictionary] objectForKey:@"CFBundleDisplayName"] forKey:@"appname"];
+ [dict setObject:[[[NSBundle mainBundle] infoDictionary] objectForKey:@"CFBundleName"] forKey:@"appname"];
```

Can you please make this fix in your lib? Thanks!

**Comment by melke** [comment]
Thanks again! I released a new version, 2.0.2, where I fallback to CFBundleName if CFBundleDisplayName is nil.
