### ISSUE TITLE
Ability to not include rawlogmessage in the payload

### ISSUE THREAD

**Issue by nickbit** [melke/LogglyLogger-CocoaLumberjack#18]
It would be great if there is a way to exclude the rawlogmessage which makes it hard to read the logs

**Comment by melke** [comment]
That's a good idea! I also find it annoying that those rawlogmessage:s are posted also for log messages that are valid JSON. I have no idea why I did it that way from the beginning :) 
To not break anything for existing users, I will add a boolean property on the LogglyFormatter, alwaysIncludeRawMessage, that will be default set to YES, which will keep current behavior as is. If you want to get rid of the rawlogmessages for JSON formatted log entries, set the property to NO.

I will do this in the next release.

**Comment by nickbit** [comment]
Thank you very much!

**Comment by melke** [comment]
Hi @nickbit I just released 2.0.3 that includes this
