### ISSUE TITLE
How to set userId

### ISSUE THREAD

**Issue by cerupcat** [melke/LogglyLogger-CocoaLumberjack#23]
I'm confused on how to set the userId. I see it in LogglyFields, but I don't see a way to access fields.

**Comment by melke** [comment]
Hi @cerupcat 

You would need to create your own instance of LogglyFields and use another init method for LogglyFormatter, which uses this instance. Like this:

```swift
    LogglyFields *logglyFields = [[LogglyFields alloc] init];
    LogglyFormatter *logglyFormatter = [[LogglyFormatter alloc] initWithLogglyFieldsDelegate:logglyFields];
    logglyFields.userid = @"lukeskywalker";
    LogglyLogger *logglyLogger = [[LogglyLogger alloc] init];
    logglyFormatter.alwaysIncludeRawMessage = NO;
    [logglyLogger setLogFormatter:logglyFormatter];
```

Note that you don't need to set the userid immediately. If you keep a reference around to ´logglyFields´ you can set the userid later on.

**Comment by cerupcat** [comment]
Thanks! I missed that you could just pass in the LogglyFields as the delegate. Thanks again!
