### ISSUE TITLE
Would you please update CocoaLumberjack dependency to use latest?

### ISSUE THREAD

**Issue by dkharrat** [melke/LogglyLogger-CocoaLumberjack#24]
CocoaLumberjack 2.2.0 is out, but LogglyLogger-CocoaLumberjack requires CocoaLumberjack 2.0.x. Would you please update the library to use the latest CocoaLumberjack? The latest version has critical fixes to support Swift 2.

Thanks!

**Comment by melke** [comment]
Thank for your feedback! Much appreciated. This is now fixed in release 2.2.0

**Comment by dkharrat** [comment]
Awesome, much appreciated!
