### ISSUE TITLE
tvOS + WatchOS support - Update to AFNetworking 3.x

### ISSUE THREAD

**Issue by mofirouz** [melke/LogglyLogger-CocoaLumberjack#25]
Hi there,

Thanks for providing this great library.

I was wondering if you could update it to use AFN3.x as I would like to have support for watchOS and tvOS as well?

Kind regards,
Mo.

**Comment by melke** [comment]
Hi @mofirouz Thanks for the feedback. I removed the dependancy to AFNetworking altogether. I'm now using the standard NSURLSession for the requests. This change is in the newly pushed 2.3.0 release.

**Comment by mofirouz** [comment]
Hi @melke - thanks for the quick turn around on this.

Yep this would solve the problem for me :)

Thanks ever so much.
Cheers,
Mo.
