### ISSUE TITLE
Would you please update CocoaLumberjack dependency to use latest?

### ISSUE THREAD

**Issue by dkharrat** [melke/LogglyLogger-CocoaLumberjack#37]
CocoaLumberjack 3.0.0 is out, with fixes for XCode 8 and Swift. Would you please release a version of this logger with the new CocoaLumberjack dependency?

Thanks!

**Comment by emes** [comment]
+1 That would be great!

**Comment by melke** [comment]
Hi, thanks for the feedback. The next months ahead I will have a hard time finding time for this. All PR:s are very welcome

**Comment by melke** [comment]
Hi @dkharrat and @emes LogglyLogger-CocoaLumberjack is now updated. Podspec is pushed and uses 3.0 of CocoaLumberjack.

**Comment by emes** [comment]
@melke Many thanks!
